// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as Tester from "./tester.js";
export {
    Tester
};

export type {
    Config,
    DiagnoseResult,
    Hop,
    LatencyOptions,
    LatencyResult,
    Phase,
    Progress,
    Series,
    ServerInfo,
    SpeedOptions,
    SpeedResult,
    Stats,
    Step,
    TraceOptions,
    TraceResult
} from "./models.js";
