// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Config is everything the UI collects to reach a MySQL server.
 */
export interface Config {
    "host": string;
    "port": number;
    "user": string;
    "password": string;
    "database": string;

    /**
     * TLS is one of "false" (default), "preferred", "true", "skip-verify".
     */
    "tls": string;

    /**
     * ConnectTimeoutSec bounds the TCP dial + handshake. 0 means 10s.
     */
    "connectTimeoutSec": number;
}

/**
 * DiagnoseResult is the whole report for one "Diagnose" run.
 */
export interface DiagnoseResult {
    "ok": boolean;
    "steps": Step[] | null;
    "server": ServerInfo;
    "warnings": string[] | null;
    "totalMs": number;
}

/**
 * Hop is one TTL step on the path.
 */
export interface Hop {
    "ttl": number;
    "addr": string;
    "host": string;

    /**
     * ms; -1 means no reply
     */
    "rtts": number[] | null;
    "avgMs": number;
    "final": boolean;
    "note": string;
}

/**
 * LatencyOptions controls one latency run.
 */
export interface LatencyOptions {
    "config": Config;

    /**
     * Count is how many probes to send per series. 0 means 20.
     */
    "count": number;

    /**
     * IntervalMs paces the probes so a burst does not measure queueing. 0 means 100.
     */
    "intervalMs": number;

    /**
     * ColdConnects, if > 0, additionally measures full connect+auth+close cycles.
     */
    "coldConnects": number;
}

/**
 * LatencyResult holds every series from one run.
 */
export interface LatencyResult {
    "series": Series[] | null;
    "verdict": string;
    "warnings": string[] | null;
}

/**
 * Phase is one timed stage of the speed test.
 */
export interface Phase {
    "name": string;
    "ok": boolean;
    "rows": number;
    "bytes": number;
    "durationMs": number;
    "rowsPerSec": number;
    "miBPerSec": number;
    "opsPerSec": number;

    /**
     * per-operation latency, where the phase has discrete ops
     */
    "stats": Stats;
    "detail": string;
    "error": string;
    "hint": string;
}

/**
 * Progress is emitted on the "progress" event while a test runs, so the UI can
 * show something during a run that takes minutes.
 */
export interface Progress {
    /**
     * diagnose | latency | speedtest | trace
     */
    "kind": string;
    "message": string;
    "pct": number;
}

/**
 * Series is one set of probes of a single kind.
 */
export interface Series {
    "name": string;

    /**
     * ms; -1 marks a failed probe
     */
    "samples": number[] | null;
    "sent": number;
    "lost": number;
    "stats": Stats;
    "error": string;
}

/**
 * ServerInfo is what the server says about itself once we are in.
 */
export interface ServerInfo {
    "version": string;
    "versionComment": string;

    /**
     * MySQL, MariaDB, Percona...
     */
    "flavor": string;
    "major": number;
    "minor": number;

    /**
     * within the 5.6 - 8.x range this tool targets
     */
    "supported": boolean;
    "resolvedAddr": string;
    "connectionId": number;
    "tlsCipher": string;
    "characterSet": string;
    "collation": string;
    "timeZone": string;
    "sqlMode": string;
    "maxConnections": number;
    "threadsConnected": number;
    "maxAllowedPacket": number;
    "waitTimeoutSec": number;
    "uptimeSec": number;
    "readOnly": boolean;
    "currentUser": string;
    "grants": string[] | null;
    "clockSkewMs": number;
}

/**
 * SpeedOptions controls one throughput run.
 */
export interface SpeedOptions {
    "config": Config;

    /**
     * Rows to insert in the bulk phase. 0 means 5000.
     */
    "rows": number;

    /**
     * PayloadBytes per row. 0 means 256.
     */
    "payloadBytes": number;

    /**
     * BatchSize is rows per INSERT statement. 0 means 200. Capped to fit max_allowed_packet.
     */
    "batchSize": number;

    /**
     * Transactions is how many single-row commit cycles to time. 0 means 100.
     */
    "transactions": number;

    /**
     * Concurrency is the number of parallel connections. 0 means 1.
     */
    "concurrency": number;

    /**
     * KeepTable leaves the test table behind for inspection.
     */
    "keepTable": boolean;
}

/**
 * SpeedResult is the whole throughput report.
 */
export interface SpeedResult {
    "ok": boolean;
    "table": string;
    "phases": Phase[] | null;
    "summary": string;
    "warnings": string[] | null;
    "totalMs": number;
}

/**
 * Stats are the summary numbers reported for any set of timing samples (ms).
 */
export interface Stats {
    "min": number;
    "max": number;
    "avg": number;
    "p50": number;
    "p95": number;
    "p99": number;
    "stddev": number;

    /**
     * Jitter is the mean absolute difference between consecutive samples,
     * which is what makes an interactive connection feel bad even at a low average.
     */
    "jitter": number;
}

/**
 * Step is one stage of the connection handshake, timed independently so a slow
 * connection can be blamed on the right layer (DNS vs TCP vs auth vs query).
 */
export interface Step {
    "name": string;
    "ok": boolean;
    "skipped": boolean;
    "durationMs": number;
    "detail": string;
    "error": string;
    "hint": string;
}

/**
 * TraceOptions controls one traceroute run.
 */
export interface TraceOptions {
    "config": Config;

    /**
     * MaxHops caps the TTL. 0 means 30.
     */
    "maxHops": number;

    /**
     * Probes per hop. 0 means 3.
     */
    "probes": number;

    /**
     * TimeoutMs to wait for each probe. 0 means 1000.
     */
    "timeoutMs": number;

    /**
     * ResolveNames does reverse DNS on each hop.
     */
    "resolveNames": boolean;
}

/**
 * TraceResult is the whole path plus a check that the MySQL port itself answers.
 */
export interface TraceResult {
    "target": string;
    "targetIp": string;
    "mode": string;
    "hops": Hop[] | null;
    "reached": boolean;
    "portOpen": boolean;
    "portMs": number;
    "portError": string;
    "note": string;
    "totalHops": number;

    /**
     * TTL of the biggest latency jump
     */
    "longestHop": number;
}
