// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Tester is the single service bound to the frontend. Only one test runs at a
 * time: starting a new one cancels whatever was in flight.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel stops the running test. Safe to call when nothing is running.
 */
export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(3006495727);
}

/**
 * CheckForUpdates opens the framework's update window, which reports "up to
 * date" or walks download, verify, install and restart. Released builds only.
 */
export function CheckForUpdates(): $CancellablePromise<void> {
    return $Call.ByID(14306916);
}

/**
 * Diagnose walks the connection one layer at a time and stops at the first failure.
 * Named results so the deferred TotalMs assignment lands in what the caller gets.
 */
export function Diagnose(cfg: $models.Config): $CancellablePromise<$models.DiagnoseResult> {
    return $Call.ByID(2747142849, cfg);
}

/**
 * Latency measures three different things people all call "latency":
 * the TCP round trip, a query on an already open connection, and the cost of
 * opening a brand new connection. Pool sizing depends on the gap between them.
 */
export function Latency(opts: $models.LatencyOptions): $CancellablePromise<$models.LatencyResult> {
    return $Call.ByID(845939277, opts);
}

/**
 * ListDatabases returns the schemas this account can see, for the UI dropdown.
 */
export function ListDatabases(cfg: $models.Config): $CancellablePromise<string[] | null> {
    return $Call.ByID(1924928889, cfg);
}

/**
 * SpeedTest inserts, reads, updates, commits and deletes real rows in a
 * throwaway table, so the numbers reflect the whole client-server path rather
 * than a synthetic ping.
 * Named results so the deferred TotalMs assignment lands in what the caller gets.
 */
export function SpeedTest(opts: $models.SpeedOptions): $CancellablePromise<$models.SpeedResult> {
    return $Call.ByID(2929695784, opts);
}

/**
 * Trace walks the path to the database host with TTL-limited ICMP echoes, then
 * confirms the last mile by opening a real TCP connection to the MySQL port.
 * A hop showing * is a router that declines to answer, not necessarily a fault.
 */
export function Trace(opts: $models.TraceOptions): $CancellablePromise<$models.TraceResult> {
    return $Call.ByID(853838722, opts);
}

/**
 * Version is the running version, or "dev" for a local build.
 */
export function Version(): $CancellablePromise<string> {
    return $Call.ByID(3138310587);
}
